#include "xenon/generation_pipeline.hpp"
#include <utility>
namespace xenon {
GenerationPipeline::GenerationPipeline(ModelRouter router):router_(std::move(router)){}
void GenerationPipeline::set_music_memory(OrganicMusicMemory memory){memory_=std::move(memory);} void GenerationPipeline::clear_music_memory() noexcept{memory_.reset();}
const OrganicMusicMemory* GenerationPipeline::music_memory() const noexcept{return memory_?&*memory_:nullptr;}
void GenerationPipeline::set_composer_perceptual_target(SynesthesiaState state){composer_target_=std::move(state);} void GenerationPipeline::clear_composer_perceptual_target() noexcept{composer_target_.reset();}
const SynesthesiaState* GenerationPipeline::composer_perceptual_target() const noexcept{return composer_target_?&*composer_target_:nullptr;}
GenerationRequest GenerationPipeline::recall(GenerationRequest r) const{return memory_?memory_->apply_to(std::move(r)):r;}
ComposerAgentContext GenerationPipeline::composer_context() const{ComposerAgentContext c;c.memory=memory_?&*memory_:nullptr;c.perceptual_target=composer_target_;return c;}
EnsemblePlan GenerationPipeline::conduct(const GenerationRequest& r,const ComposerAgentPlan& a,const CompositionPlan& p,const EtherDNARecord* parent,const std::string& fp) const{EtherDNARecord provisional;auto shared=parent;if(!shared){provisional=dna_.capture(r,p,fp);shared=&provisional;}MusicianAgentContext c;c.composer_plan=&a;c.dna=shared;c.locks=r.control.locks;return musicians_.conduct(c);}
GenerationResult GenerationPipeline::generate(const GenerationRequest& in,const std::filesystem::path& out,const std::string& fp){auto remembered=recall(in);auto controlled=control_.compile(remembered);auto ap=composer_agent_.plan(controlled.request,composer_context());auto p=composer_agent_.to_composition_plan(ap);auto c=composer_agent_.compile(controlled.request,ap);c=composer_.compile(c,p);auto e=conduct(c,ap,p,nullptr,fp);c=musicians_.compile(c,e);auto route=router_.route(c);auto artifact=router_.generate(c,out);auto dna=dna_.capture(c,p,fp);return {std::move(artifact),p,dna,route,e};}
GenerationResult GenerationPipeline::generate_evolved(const GenerationRequest& in,const std::filesystem::path& out,const EtherDNARecord& parent,std::vector<MutationEvent> mutations){auto remembered=recall(in);auto controlled=control_.compile(remembered);auto ap=composer_agent_.plan(controlled.request,composer_context());auto p=composer_agent_.to_composition_plan(ap);auto c=composer_agent_.compile(controlled.request,ap);c=composer_.compile(c,p);auto e=conduct(c,ap,p,&parent,parent.fingerprint);c=musicians_.compile(c,e);auto route=router_.route(c);auto artifact=router_.generate(c,out);auto dna=dna_.evolve(parent,c,p,std::move(mutations));return {std::move(artifact),p,dna,route,e};}
GenerationBatch GenerationPipeline::generate_candidates(const GenerationRequest& in,const std::filesystem::path& out,const std::string& fp){auto remembered=recall(in);auto controlled=control_.compile(remembered);auto ap=composer_agent_.plan(controlled.request,composer_context());auto p=composer_agent_.to_composition_plan(ap);auto c=composer_agent_.compile(controlled.request,ap);c=composer_.compile(c,p);auto e=conduct(c,ap,p,nullptr,fp);c=musicians_.compile(c,e);auto dna=dna_.capture(c,p,fp);GenerationBatch b;auto attempts=router_.generate_all(c,out);for(auto& a:attempts){if(a.success)b.successes.push_back({std::move(a.artifact),p,dna,a.route,e});else b.failures.push_back({a.route,std::move(a.error)});}return b;}
const ModelRouter& GenerationPipeline::router() const noexcept{return router_;} ModelRouter& GenerationPipeline::mutable_router() noexcept{return router_;}
} // namespace xenon
