#include "xenon/model_router.hpp"

#include <algorithm>
#include <cctype>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <utility>

namespace xenon {
namespace {
ProviderCapability mode_capability(GenerationMode mode){switch(mode){case GenerationMode::TextToInstrumental:return ProviderCapability::TextToInstrumental;case GenerationMode::Variation:return ProviderCapability::Variation;case GenerationMode::Extend:return ProviderCapability::Extend;case GenerationMode::AudioToAudio:return ProviderCapability::AudioToAudio;case GenerationMode::ReplaceSection:return ProviderCapability::ReplaceSection;}return ProviderCapability::None;}
ProviderCapability role_capability(RenderIntent intent){switch(intent){case RenderIntent::Draft:return ProviderCapability::DraftRole;case RenderIntent::Quality:return ProviderCapability::QualityRole;case RenderIntent::Control:return ProviderCapability::ControlRole;case RenderIntent::Vocal:return ProviderCapability::VocalRole;case RenderIntent::Auto:return ProviderCapability::None;}return ProviderCapability::None;}
RenderIntent resolve_intent(const GenerationRequest& r){if(r.render_intent!=RenderIntent::Auto)return r.render_intent;return r.mode==GenerationMode::TextToInstrumental?RenderIntent::Quality:RenderIntent::Control;}
bool needs_temporal_control(const GenerationRequest&r){return r.mode==GenerationMode::ReplaceSection||r.control.edit_start_seconds>=0.0||r.control.edit_end_seconds>=0.0;}
bool supports_details(ProviderCapabilities caps,const GenerationRequest&r){if(r.control.locks!=0&&!has_capability(caps,ProviderCapability::ComponentLocks))return false;if(!r.control.drum_reference.empty()&&!has_capability(caps,ProviderCapability::DrumConditioning))return false;if(!r.control.melody_reference.empty()&&!has_capability(caps,ProviderCapability::MelodyConditioning))return false;if(!r.control.chord_progression.empty()&&!has_capability(caps,ProviderCapability::HarmonyConditioning))return false;if(needs_temporal_control(r)&&!has_capability(caps,ProviderCapability::TemporalControl))return false;return true;}
std::string safe_component(std::string value){for(auto&ch:value){const auto c=static_cast<unsigned char>(ch);if(!std::isalnum(c)&&ch!='-'&&ch!='_')ch='_';}if(value.empty())value="backend";return value;}
}
void ModelRouter::add_provider(std::unique_ptr<IModelBackend> backend,int priority){if(!backend)throw std::invalid_argument("XENON cannot register a null model backend");providers_.push_back({std::shared_ptr<IModelBackend>(std::move(backend)),priority});}
void ModelRouter::add_provider(std::shared_ptr<IModelBackend> backend,int priority){if(!backend)throw std::invalid_argument("XENON cannot register a null model backend");providers_.push_back({std::move(backend),priority});}
void ModelRouter::set_policy(BackendPolicy p) noexcept{policy_=p;} const BackendPolicy& ModelRouter::policy() const noexcept{return policy_;}
std::size_t ModelRouter::provider_count() const noexcept{return providers_.size();}
std::vector<ProviderInfo> ModelRouter::providers() const{std::vector<ProviderInfo> r;r.reserve(providers_.size());for(const auto&s:providers_)r.push_back({std::string{s.backend->name()},s.backend->capabilities(),s.backend->runtime_type(),s.priority});return r;}
bool ModelRouter::eligible(const ProviderSlot&s,const GenerationRequest&r,RenderIntent ri) const{const auto caps=s.backend->capabilities();const auto runtime=s.backend->runtime_type();const auto rm=mode_capability(r.mode);const auto rr=role_capability(ri);const bool ref=!r.reference_audio.empty();if(!policy_.allows(runtime))return false;if(!has_capability(caps,rm))return false;if(rr!=ProviderCapability::None&&!has_capability(caps,rr))return false;if(ref&&!has_capability(caps,ProviderCapability::ReferenceAudio))return false;return supports_details(caps,r);}
const ModelRouter::ProviderSlot& ModelRouter::select_provider(const GenerationRequest&r,RenderIntent ri) const{if(providers_.empty())throw std::runtime_error("XENON has no model backends registered");const auto rr=role_capability(ri);const bool ref=!r.reference_audio.empty();const ProviderSlot*best=nullptr;int best_score=std::numeric_limits<int>::min();for(const auto&s:providers_){if(!eligible(s,r,ri))continue;const auto caps=s.backend->capabilities();int score=s.priority+policy_.runtime_score(s.backend->runtime_type());if(has_capability(caps,rr))score+=1000;if(ref&&has_capability(caps,ProviderCapability::ReferenceAudio))score+=100;if(!best||score>best_score){best=&s;best_score=score;}}if(!best)throw std::runtime_error("No XENON backend satisfies the generation requirements and runtime policy");return *best;}
RouteDecision ModelRouter::route(const GenerationRequest&r) const{const auto ri=resolve_intent(r);const auto&s=select_provider(r,ri);return {std::string{s.backend->name()},r.render_intent,ri,s.backend->capabilities(),s.backend->runtime_type()};}
GenerationArtifact ModelRouter::generate(const GenerationRequest&r,const std::filesystem::path&out){if(r.prompt.empty())throw std::invalid_argument("Generation prompt cannot be empty");if(r.duration_seconds<=0.0||r.duration_seconds>600.0)throw std::invalid_argument("Generation duration must be within (0, 600] seconds");const auto ri=resolve_intent(r);const auto&s=select_provider(r,ri);return s.backend->generate(r,out);}
std::vector<BackendGenerationAttempt> ModelRouter::generate_all(const GenerationRequest&r,const std::filesystem::path&out){if(r.prompt.empty())throw std::invalid_argument("Generation prompt cannot be empty");if(r.duration_seconds<=0.0||r.duration_seconds>600.0)throw std::invalid_argument("Generation duration must be within (0, 600] seconds");const auto ri=resolve_intent(r);std::vector<BackendGenerationAttempt>a;for(auto&s:providers_){if(!eligible(s,r,ri))continue;BackendGenerationAttempt x;x.route={std::string{s.backend->name()},r.render_intent,ri,s.backend->capabilities(),s.backend->runtime_type()};try{x.artifact=s.backend->generate(r,out/safe_component(x.route.provider_name));x.success=true;}catch(const std::exception&e){x.error=e.what();}catch(...){x.error="unknown backend generation failure";}a.push_back(std::move(x));}if(a.empty())throw std::runtime_error("No XENON backend is eligible for candidate fan-out");return a;}
} // namespace xenon
